### ISSUE TITLE
Not working with Sitecore v9.3 and .NET 4.8 framework

### ISSUE THREAD

**Issue by maxslabyak** [jraps20/SitecoreFriendlyErrors#1]
Some of the pipeline methods in Sitecore changed, so the code no longer works with v9.3

**Comment by jraps20** [comment]
Thanks @maxslabyak . I will review.

**Comment by jraps20** [comment]
Exception:

![image](https://user-images.githubusercontent.com/392080/73025548-66d8fd80-3df5-11ea-8a3d-80c12be3b3a9.png)

**Comment by maxslabyak** [comment]
I think you need to update the dependencyinjection

https://doc.sitecore.com/developers/93/sitecore-experience-manager/en/dependency-injection.html

**Comment by jraps20** [comment]
I have a working copy locally. The breaking changes were marked as obsolete in 9.0 and now in 9.3 they are officially broken. Just trying to package it up and ensure people on 8.x don't upgrade as it will only be compatible with 9.x series.

**Comment by maxslabyak** [comment]
sweet!

**Comment by jraps20** [comment]
Pull Request: #2

**Comment by jraps20** [comment]
Pull request completed, NuGet package published.
